CREATE TABLE `neetcode` (
	`id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,
	`leetcode_question_link` text NOT NULL,
	`neetcode_question_link` text NOT NULL,
	`difficulty` text NOT NULL,
	`tag` text NOT NULL,
	`blind_75` integer NOT NULL,
	`neetcode_150` integer NOT NULL,
	`neetcode_250` integer NOT NULL
);
--> statement-breakpoint
CREATE UNIQUE INDEX `neetcode_leetcode_question_link_unique` ON `neetcode` (`leetcode_question_link`);
--> statement-breakpoint
INSERT INTO `neetcode` (`leetcode_question_link`, `neetcode_question_link`, `difficulty`, `tag`, `blind_75`, `neetcode_150`, `neetcode_250`) VALUES
('https://leetcode.com/problems/concatenation-of-array/', 'https://neetcode.io/problems/concatenation-of-array', 'Easy', 'arrays and hashing', 0, 0, 1),
('https://leetcode.com/problems/contains-duplicate/', 'https://neetcode.io/problems/contains-duplicate', 'Easy', 'arrays and hashing', 1, 1, 1),
('https://leetcode.com/problems/valid-anagram/', 'https://neetcode.io/problems/valid-anagram', 'Easy', 'arrays and hashing', 1, 1, 1),
('https://leetcode.com/problems/two-sum/', 'https://neetcode.io/problems/two-sum', 'Easy', 'arrays and hashing', 1, 1, 1),
('https://leetcode.com/problems/longest-common-prefix/', 'https://neetcode.io/problems/longest-common-prefix', 'Easy', 'arrays and hashing', 0, 0, 1),
('https://leetcode.com/problems/group-anagrams/', 'https://neetcode.io/problems/group-anagrams', 'Medium', 'arrays and hashing', 1, 1, 1),
('https://leetcode.com/problems/remove-element/', 'https://neetcode.io/problems/remove-element', 'Easy', 'arrays and hashing', 0, 0, 1),
('https://leetcode.com/problems/majority-element/', 'https://neetcode.io/problems/majority-element', 'Easy', 'arrays and hashing', 0, 0, 1),
('https://leetcode.com/problems/design-hashset/', 'https://neetcode.io/problems/design-hashset', 'Easy', 'arrays and hashing', 0, 0, 1),
('https://leetcode.com/problems/design-hashmap/', 'https://neetcode.io/problems/design-hashmap', 'Easy', 'arrays and hashing', 0, 0, 1),
('https://leetcode.com/problems/sort-an-array/', 'https://neetcode.io/problems/sort-an-array', 'Medium', 'arrays and hashing', 0, 0, 1),
('https://leetcode.com/problems/sort-colors/', 'https://neetcode.io/problems/sort-colors', 'Medium', 'arrays and hashing', 0, 0, 1),
('https://leetcode.com/problems/top-k-frequent-elements/', 'https://neetcode.io/problems/top-k-frequent-elements', 'Medium', 'arrays and hashing', 1, 1, 1),
('https://leetcode.com/problems/encode-and-decode-strings/', 'https://neetcode.io/problems/encode-and-decode-strings', 'Medium', 'arrays and hashing', 1, 1, 1),
('https://leetcode.com/problems/range-sum-query-2d-immutable/', 'https://neetcode.io/problems/range-sum-query-2d-immutable', 'Medium', 'arrays and hashing', 0, 0, 1),
('https://leetcode.com/problems/product-of-array-except-self/', 'https://neetcode.io/problems/product-of-array-except-self', 'Medium', 'arrays and hashing', 1, 1, 1),
('https://leetcode.com/problems/valid-sudoku/', 'https://neetcode.io/problems/valid-sudoku', 'Medium', 'arrays and hashing', 0, 1, 1),
('https://leetcode.com/problems/longest-consecutive-sequence/', 'https://neetcode.io/problems/longest-consecutive-sequence', 'Medium', 'arrays and hashing', 1, 1, 1),
('https://leetcode.com/problems/best-time-to-buy-and-sell-stock-ii/', 'https://neetcode.io/problems/best-time-to-buy-and-sell-stock-ii', 'Medium', 'arrays and hashing', 0, 0, 1),
('https://leetcode.com/problems/majority-element-ii/', 'https://neetcode.io/problems/majority-element-ii', 'Medium', 'arrays and hashing', 0, 0, 1),
('https://leetcode.com/problems/subarray-sum-equals-k/', 'https://neetcode.io/problems/subarray-sum-equals-k', 'Medium', 'arrays and hashing', 0, 0, 1),
('https://leetcode.com/problems/first-missing-positive/', 'https://neetcode.io/problems/first-missing-positive', 'Hard', 'arrays and hashing', 0, 0, 1),
('https://leetcode.com/problems/reverse-string/', 'https://neetcode.io/problems/reverse-string', 'Easy', 'two pointers', 0, 0, 1),
('https://leetcode.com/problems/valid-palindrome/', 'https://neetcode.io/problems/valid-palindrome', 'Easy', 'two pointers', 1, 1, 1),
('https://leetcode.com/problems/valid-palindrome-ii/', 'https://neetcode.io/problems/valid-palindrome-ii', 'Easy', 'two pointers', 0, 0, 1),
('https://leetcode.com/problems/merge-strings-alternately/', 'https://neetcode.io/problems/merge-strings-alternately', 'Easy', 'two pointers', 0, 0, 1),
('https://leetcode.com/problems/merge-sorted-array/', 'https://neetcode.io/problems/merge-sorted-array', 'Easy', 'two pointers', 0, 0, 1),
('https://leetcode.com/problems/remove-duplicates-from-sorted-array/', 'https://neetcode.io/problems/remove-duplicates-from-sorted-array', 'Easy', 'two pointers', 0, 0, 1),
('https://leetcode.com/problems/two-sum-ii-input-array-is-sorted/', 'https://neetcode.io/problems/two-sum-ii-input-array-is-sorted', 'Medium', 'two pointers', 0, 1, 1),
('https://leetcode.com/problems/3sum/', 'https://neetcode.io/problems/3sum', 'Medium', 'two pointers', 1, 1, 1),
('https://leetcode.com/problems/4sum/', 'https://neetcode.io/problems/4sum', 'Medium', 'two pointers', 0, 0, 1),
('https://leetcode.com/problems/rotate-array/', 'https://neetcode.io/problems/rotate-array', 'Medium', 'two pointers', 0, 0, 1),
('https://leetcode.com/problems/container-with-most-water/', 'https://neetcode.io/problems/container-with-most-water', 'Medium', 'two pointers', 1, 1, 1),
('https://leetcode.com/problems/boats-to-save-people/', 'https://neetcode.io/problems/boats-to-save-people', 'Medium', 'two pointers', 0, 0, 1),
('https://leetcode.com/problems/trapping-rain-water/', 'https://neetcode.io/problems/trapping-rain-water', 'Hard', 'two pointers', 0, 1, 1),
('https://leetcode.com/problems/contains-duplicate-ii/', 'https://neetcode.io/problems/contains-duplicate-ii', 'Easy', 'sliding window', 0, 0, 1),
('https://leetcode.com/problems/best-time-to-buy-and-sell-stock/', 'https://neetcode.io/problems/best-time-to-buy-and-sell-stock', 'Easy', 'sliding window', 1, 1, 1),
('https://leetcode.com/problems/longest-substring-without-repeating-characters/', 'https://neetcode.io/problems/longest-substring-without-repeating-characters', 'Medium', 'sliding window', 1, 1, 1),
('https://leetcode.com/problems/longest-repeating-character-replacement/', 'https://neetcode.io/problems/longest-repeating-character-replacement', 'Medium', 'sliding window', 1, 1, 1),
('https://leetcode.com/problems/permutation-in-string/', 'https://neetcode.io/problems/permutation-in-string', 'Medium', 'sliding window', 0, 1, 1),
('https://leetcode.com/problems/minimum-size-subarray-sum/', 'https://neetcode.io/problems/minimum-size-subarray-sum', 'Medium', 'sliding window', 0, 0, 1),
('https://leetcode.com/problems/find-k-closest-elements/', 'https://neetcode.io/problems/find-k-closest-elements', 'Medium', 'sliding window', 0, 0, 1),
('https://leetcode.com/problems/minimum-window-substring/', 'https://neetcode.io/problems/minimum-window-substring', 'Hard', 'sliding window', 1, 1, 1),
('https://leetcode.com/problems/sliding-window-maximum/', 'https://neetcode.io/problems/sliding-window-maximum', 'Hard', 'sliding window', 0, 1, 1),
('https://leetcode.com/problems/baseball-game/', 'https://neetcode.io/problems/baseball-game', 'Easy', 'stack', 0, 0, 1),
('https://leetcode.com/problems/valid-parentheses/', 'https://neetcode.io/problems/valid-parentheses', 'Easy', 'stack', 1, 1, 1),
('https://leetcode.com/problems/implement-stack-using-queues/', 'https://neetcode.io/problems/implement-stack-using-queues', 'Easy', 'stack', 0, 0, 1),
('https://leetcode.com/problems/implement-queue-using-stacks/', 'https://neetcode.io/problems/implement-queue-using-stacks', 'Easy', 'stack', 0, 0, 1),
('https://leetcode.com/problems/min-stack/', 'https://neetcode.io/problems/min-stack', 'Medium', 'stack', 0, 1, 1),
('https://leetcode.com/problems/evaluate-reverse-polish-notation/', 'https://neetcode.io/problems/evaluate-reverse-polish-notation', 'Medium', 'stack', 0, 1, 1),
('https://leetcode.com/problems/generate-parentheses/', 'https://neetcode.io/problems/generate-parentheses', 'Medium', 'stack', 0, 1, 1),
('https://leetcode.com/problems/asteroid-collision/', 'https://neetcode.io/problems/asteroid-collision', 'Medium', 'stack', 0, 0, 1),
('https://leetcode.com/problems/daily-temperatures/', 'https://neetcode.io/problems/daily-temperatures', 'Medium', 'stack', 0, 1, 1),
('https://leetcode.com/problems/online-stock-span/', 'https://neetcode.io/problems/online-stock-span', 'Medium', 'stack', 0, 0, 1),
('https://leetcode.com/problems/car-fleet/', 'https://neetcode.io/problems/car-fleet', 'Medium', 'stack', 0, 1, 1),
('https://leetcode.com/problems/simplify-path/', 'https://neetcode.io/problems/simplify-path', 'Medium', 'stack', 0, 0, 1),
('https://leetcode.com/problems/decode-string/', 'https://neetcode.io/problems/decode-string', 'Medium', 'stack', 0, 0, 1),
('https://leetcode.com/problems/maximum-frequency-stack/', 'https://neetcode.io/problems/maximum-frequency-stack', 'Hard', 'stack', 0, 0, 1),
('https://leetcode.com/problems/largest-rectangle-in-histogram/', 'https://neetcode.io/problems/largest-rectangle-in-histogram', 'Hard', 'stack', 0, 1, 1),
('https://leetcode.com/problems/binary-search/', 'https://neetcode.io/problems/binary-search', 'Easy', 'binary search', 0, 1, 1),
('https://leetcode.com/problems/search-insert-position/', 'https://neetcode.io/problems/search-insert-position', 'Easy', 'binary search', 0, 0, 1),
('https://leetcode.com/problems/guess-number-higher-or-lower/', 'https://neetcode.io/problems/guess-number-higher-or-lower', 'Easy', 'binary search', 0, 0, 1),
('https://leetcode.com/problems/sqrtx/', 'https://neetcode.io/problems/sqrtx', 'Easy', 'binary search', 0, 0, 1),
('https://leetcode.com/problems/search-a-2d-matrix/', 'https://neetcode.io/problems/search-a-2d-matrix', 'Medium', 'binary search', 0, 1, 1),
('https://leetcode.com/problems/koko-eating-bananas/', 'https://neetcode.io/problems/koko-eating-bananas', 'Medium', 'binary search', 0, 1, 1),
('https://leetcode.com/problems/capacity-to-ship-packages/', 'https://neetcode.io/problems/capacity-to-ship-packages', 'Medium', 'binary search', 0, 0, 1),
('https://leetcode.com/problems/find-minimum-in-rotated-sorted-array/', 'https://neetcode.io/problems/find-minimum-in-rotated-sorted-array', 'Medium', 'binary search', 1, 1, 1),
('https://leetcode.com/problems/search-in-rotated-sorted-array/', 'https://neetcode.io/problems/search-in-rotated-sorted-array', 'Medium', 'binary search', 1, 1, 1),
('https://leetcode.com/problems/search-in-rotated-sorted-array-ii/', 'https://neetcode.io/problems/search-in-rotated-sorted-array-ii', 'Medium', 'binary search', 0, 0, 1),
('https://leetcode.com/problems/time-based-key-value-store/', 'https://neetcode.io/problems/time-based-key-value-store', 'Medium', 'binary search', 0, 1, 1),
('https://leetcode.com/problems/split-array-largest-sum/', 'https://neetcode.io/problems/split-array-largest-sum', 'Hard', 'binary search', 0, 0, 1),
('https://leetcode.com/problems/median-of-two-sorted-arrays/', 'https://neetcode.io/problems/median-of-two-sorted-arrays', 'Hard', 'binary search', 0, 1, 1),
('https://leetcode.com/problems/find-in-mountain-array/', 'https://neetcode.io/problems/find-in-mountain-array', 'Hard', 'binary search', 0, 0, 1),
('https://leetcode.com/problems/reverse-linked-list/', 'https://neetcode.io/problems/reverse-linked-list', 'Easy', 'linked list', 1, 1, 1),
('https://leetcode.com/problems/merge-two-sorted-lists/', 'https://neetcode.io/problems/merge-two-sorted-lists', 'Easy', 'linked list', 1, 1, 1),
('https://leetcode.com/problems/linked-list-cycle/', 'https://neetcode.io/problems/linked-list-cycle', 'Easy', 'linked list', 1, 1, 1),
('https://leetcode.com/problems/reorder-list/', 'https://neetcode.io/problems/reorder-list', 'Medium', 'linked list', 1, 1, 1),
('https://leetcode.com/problems/remove-nth-node-from-end-of-list/', 'https://neetcode.io/problems/remove-nth-node-from-end-of-list', 'Medium', 'linked list', 1, 1, 1),
('https://leetcode.com/problems/copy-list-with-random-pointer/', 'https://neetcode.io/problems/copy-list-with-random-pointer', 'Medium', 'linked list', 0, 1, 1),
('https://leetcode.com/problems/add-two-numbers/', 'https://neetcode.io/problems/add-two-numbers', 'Medium', 'linked list', 0, 1, 1),
('https://leetcode.com/problems/find-the-duplicate-number/', 'https://neetcode.io/problems/find-the-duplicate-number', 'Medium', 'linked list', 0, 1, 1),
('https://leetcode.com/problems/reverse-linked-list-ii/', 'https://neetcode.io/problems/reverse-linked-list-ii', 'Medium', 'linked list', 0, 0, 1),
('https://leetcode.com/problems/design-circular-queue/', 'https://neetcode.io/problems/design-circular-queue', 'Medium', 'linked list', 0, 0, 1),
('https://leetcode.com/problems/lru-cache/', 'https://neetcode.io/problems/lru-cache', 'Medium', 'linked list', 0, 1, 1),
('https://leetcode.com/problems/lfu-cache/', 'https://neetcode.io/problems/lfu-cache', 'Hard', 'linked list', 0, 0, 1),
('https://leetcode.com/problems/merge-k-sorted-lists/', 'https://neetcode.io/problems/merge-k-sorted-lists', 'Hard', 'linked list', 1, 1, 1),
('https://leetcode.com/problems/reverse-nodes-in-k-group/', 'https://neetcode.io/problems/reverse-nodes-in-k-group', 'Hard', 'linked list', 0, 1, 1),
('https://leetcode.com/problems/binary-tree-inorder-traversal/', 'https://neetcode.io/problems/binary-tree-inorder-traversal', 'Easy', 'trees', 0, 0, 1),
('https://leetcode.com/problems/binary-tree-preorder-traversal/', 'https://neetcode.io/problems/binary-tree-preorder-traversal', 'Easy', 'trees', 0, 0, 1),
('https://leetcode.com/problems/binary-tree-postorder-traversal/', 'https://neetcode.io/problems/binary-tree-postorder-traversal', 'Easy', 'trees', 0, 0, 1),
('https://leetcode.com/problems/invert-binary-tree/', 'https://neetcode.io/problems/invert-binary-tree', 'Easy', 'trees', 1, 1, 1),
('https://leetcode.com/problems/maximum-depth-of-binary-tree/', 'https://neetcode.io/problems/maximum-depth-of-binary-tree', 'Easy', 'trees', 1, 1, 1),
('https://leetcode.com/problems/diameter-of-binary-tree/', 'https://neetcode.io/problems/diameter-of-binary-tree', 'Easy', 'trees', 0, 1, 1),
('https://leetcode.com/problems/balanced-binary-tree/', 'https://neetcode.io/problems/balanced-binary-tree', 'Easy', 'trees', 0, 1, 1),
('https://leetcode.com/problems/same-tree/', 'https://neetcode.io/problems/same-tree', 'Easy', 'trees', 1, 1, 1),
('https://leetcode.com/problems/subtree-of-another-tree/', 'https://neetcode.io/problems/subtree-of-another-tree', 'Easy', 'trees', 1, 1, 1),
('https://leetcode.com/problems/lowest-common-ancestor-of-a-binary-search-tree/', 'https://neetcode.io/problems/lowest-common-ancestor-of-a-binary-search-tree', 'Medium', 'trees', 1, 1, 1),
('https://leetcode.com/problems/insert-into-a-binary-search-tree/', 'https://neetcode.io/problems/insert-into-a-binary-search-tree', 'Medium', 'trees', 0, 0, 1),
('https://leetcode.com/problems/delete-node-in-a-bst/', 'https://neetcode.io/problems/delete-node-in-a-bst', 'Medium', 'trees', 0, 0, 1),
('https://leetcode.com/problems/binary-tree-level-order-traversal/', 'https://neetcode.io/problems/binary-tree-level-order-traversal', 'Medium', 'trees', 1, 1, 1),
('https://leetcode.com/problems/binary-tree-right-side-view/', 'https://neetcode.io/problems/binary-tree-right-side-view', 'Medium', 'trees', 0, 1, 1),
('https://leetcode.com/problems/construct-quad-tree/', 'https://neetcode.io/problems/construct-quad-tree', 'Medium', 'trees', 0, 0, 1),
('https://leetcode.com/problems/count-good-nodes-in-binary-tree/', 'https://neetcode.io/problems/count-good-nodes-in-binary-tree', 'Medium', 'trees', 0, 1, 1),
('https://leetcode.com/problems/validate-binary-search-tree/', 'https://neetcode.io/problems/validate-binary-search-tree', 'Medium', 'trees', 1, 1, 1),
('https://leetcode.com/problems/kth-smallest-element-in-a-bst/', 'https://neetcode.io/problems/kth-smallest-element-in-a-bst', 'Medium', 'trees', 1, 1, 1),
('https://leetcode.com/problems/construct-binary-tree-from-preorder-and-inorder-traversal/', 'https://neetcode.io/problems/construct-binary-tree-from-preorder-and-inorder-traversal', 'Medium', 'trees', 1, 1, 1),
('https://leetcode.com/problems/house-robber-iii/', 'https://neetcode.io/problems/house-robber-iii', 'Medium', 'trees', 0, 0, 1),
('https://leetcode.com/problems/delete-leaves-with-a-given-value/', 'https://neetcode.io/problems/delete-leaves-with-a-given-value', 'Medium', 'trees', 0, 0, 1),
('https://leetcode.com/problems/binary-tree-maximum-path-sum/', 'https://neetcode.io/problems/binary-tree-maximum-path-sum', 'Hard', 'trees', 1, 1, 1),
('https://leetcode.com/problems/serialize-and-deserialize-binary-tree/', 'https://neetcode.io/problems/serialize-and-deserialize-binary-tree', 'Hard', 'trees', 1, 1, 1),
('https://leetcode.com/problems/kth-largest-element-in-a-stream/', 'https://neetcode.io/problems/kth-largest-element-in-a-stream', 'Easy', 'heap / priority queue', 0, 1, 1),
('https://leetcode.com/problems/last-stone-weight/', 'https://neetcode.io/problems/last-stone-weight', 'Easy', 'heap / priority queue', 0, 1, 1),
('https://leetcode.com/problems/k-closest-points-to-origin/', 'https://neetcode.io/problems/k-closest-points-to-origin', 'Medium', 'heap / priority queue', 0, 1, 1),
('https://leetcode.com/problems/kth-largest-element-in-an-array/', 'https://neetcode.io/problems/kth-largest-element-in-an-array', 'Medium', 'heap / priority queue', 0, 1, 1),
('https://leetcode.com/problems/task-scheduler/', 'https://neetcode.io/problems/task-scheduler', 'Medium', 'heap / priority queue', 0, 1, 1),
('https://leetcode.com/problems/design-twitter/', 'https://neetcode.io/problems/design-twitter', 'Medium', 'heap / priority queue', 0, 1, 1),
('https://leetcode.com/problems/single-threaded-cpu/', 'https://neetcode.io/problems/single-threaded-cpu', 'Medium', 'heap / priority queue', 0, 0, 1),
('https://leetcode.com/problems/reorganize-string/', 'https://neetcode.io/problems/reorganize-string', 'Medium', 'heap / priority queue', 0, 0, 1),
('https://leetcode.com/problems/longest-happy-string/', 'https://neetcode.io/problems/longest-happy-string', 'Medium', 'heap / priority queue', 0, 0, 1),
('https://leetcode.com/problems/car-pooling/', 'https://neetcode.io/problems/car-pooling', 'Medium', 'heap / priority queue', 0, 0, 1),
('https://leetcode.com/problems/find-median-from-data-stream/', 'https://neetcode.io/problems/find-median-from-data-stream', 'Hard', 'heap / priority queue', 1, 1, 1),
('https://leetcode.com/problems/ipo/', 'https://neetcode.io/problems/ipo', 'Hard', 'heap / priority queue', 0, 0, 1),
('https://leetcode.com/problems/sum-of-all-subsets-xor-total/', 'https://neetcode.io/problems/sum-of-all-subsets-xor-total', 'Easy', 'backtracking', 0, 0, 1),
('https://leetcode.com/problems/subsets/', 'https://neetcode.io/problems/subsets', 'Medium', 'backtracking', 0, 1, 1),
('https://leetcode.com/problems/combination-sum/', 'https://neetcode.io/problems/combination-sum', 'Medium', 'backtracking', 1, 1, 1),
('https://leetcode.com/problems/combination-sum-ii/', 'https://neetcode.io/problems/combination-sum-ii', 'Medium', 'backtracking', 0, 1, 1),
('https://leetcode.com/problems/combinations/', 'https://neetcode.io/problems/combinations', 'Medium', 'backtracking', 0, 0, 1),
('https://leetcode.com/problems/permutations/', 'https://neetcode.io/problems/permutations', 'Medium', 'backtracking', 0, 1, 1),
('https://leetcode.com/problems/subsets-ii/', 'https://neetcode.io/problems/subsets-ii', 'Medium', 'backtracking', 0, 1, 1),
('https://leetcode.com/problems/permutations-ii/', 'https://neetcode.io/problems/permutations-ii', 'Medium', 'backtracking', 0, 0, 1),
('https://leetcode.com/problems/word-search/', 'https://neetcode.io/problems/word-search', 'Medium', 'backtracking', 1, 1, 1),
('https://leetcode.com/problems/palindrome-partitioning/', 'https://neetcode.io/problems/palindrome-partitioning', 'Medium', 'backtracking', 0, 1, 1),
('https://leetcode.com/problems/letter-combinations-of-a-phone-number/', 'https://neetcode.io/problems/letter-combinations-of-a-phone-number', 'Medium', 'backtracking', 0, 1, 1),
('https://leetcode.com/problems/matchsticks-to-square/', 'https://neetcode.io/problems/matchsticks-to-square', 'Medium', 'backtracking', 0, 0, 1),
('https://leetcode.com/problems/partition-to-k-equal-sum-subsets/', 'https://neetcode.io/problems/partition-to-k-equal-sum-subsets', 'Medium', 'backtracking', 0, 0, 1),
('https://leetcode.com/problems/n-queens/', 'https://neetcode.io/problems/n-queens', 'Hard', 'backtracking', 0, 1, 1),
('https://leetcode.com/problems/n-queens-ii/', 'https://neetcode.io/problems/n-queens-ii', 'Hard', 'backtracking', 0, 0, 1),
('https://leetcode.com/problems/word-break-ii/', 'https://neetcode.io/problems/word-break-ii', 'Hard', 'backtracking', 0, 0, 1),
('https://leetcode.com/problems/implement-trie-prefix-tree/', 'https://neetcode.io/problems/implement-trie-prefix-tree', 'Medium', 'tries', 1, 1, 1),
('https://leetcode.com/problems/design-add-and-search-words-data-structure/', 'https://neetcode.io/problems/design-add-and-search-words-data-structure', 'Medium', 'tries', 1, 1, 1),
('https://leetcode.com/problems/extra-characters-in-a-string/', 'https://neetcode.io/problems/extra-characters-in-a-string', 'Medium', 'tries', 0, 0, 1),
('https://leetcode.com/problems/word-search-ii/', 'https://neetcode.io/problems/word-search-ii', 'Hard', 'tries', 1, 1, 1),
('https://leetcode.com/problems/island-perimeter/', 'https://neetcode.io/problems/island-perimeter', 'Easy', 'graphs', 0, 0, 1),
('https://leetcode.com/problems/verifying-an-alien-dictionary/', 'https://neetcode.io/problems/verifying-an-alien-dictionary', 'Easy', 'graphs', 0, 0, 1),
('https://leetcode.com/problems/find-the-town-judge/', 'https://neetcode.io/problems/find-the-town-judge', 'Easy', 'graphs', 0, 0, 1),
('https://leetcode.com/problems/number-of-islands/', 'https://neetcode.io/problems/number-of-islands', 'Medium', 'graphs', 1, 1, 1),
('https://leetcode.com/problems/max-area-of-island/', 'https://neetcode.io/problems/max-area-of-island', 'Medium', 'graphs', 0, 1, 1),
('https://leetcode.com/problems/clone-graph/', 'https://neetcode.io/problems/clone-graph', 'Medium', 'graphs', 1, 1, 1),
('https://leetcode.com/problems/walls-and-gates/', 'https://neetcode.io/problems/walls-and-gates', 'Medium', 'graphs', 0, 1, 1),
('https://leetcode.com/problems/rotting-oranges/', 'https://neetcode.io/problems/rotting-oranges', 'Medium', 'graphs', 0, 1, 1),
('https://leetcode.com/problems/pacific-atlantic-water-flow/', 'https://neetcode.io/problems/pacific-atlantic-water-flow', 'Medium', 'graphs', 1, 1, 1),
('https://leetcode.com/problems/surrounded-regions/', 'https://neetcode.io/problems/surrounded-regions', 'Medium', 'graphs', 0, 1, 1),
('https://leetcode.com/problems/open-the-lock/', 'https://neetcode.io/problems/open-the-lock', 'Medium', 'graphs', 0, 0, 1),
('https://leetcode.com/problems/course-schedule/', 'https://neetcode.io/problems/course-schedule', 'Medium', 'graphs', 1, 1, 1),
('https://leetcode.com/problems/course-schedule-ii/', 'https://neetcode.io/problems/course-schedule-ii', 'Medium', 'graphs', 0, 1, 1),
('https://leetcode.com/problems/graph-valid-tree/', 'https://neetcode.io/problems/graph-valid-tree', 'Medium', 'graphs', 1, 1, 1),
('https://leetcode.com/problems/course-schedule-iv/', 'https://neetcode.io/problems/course-schedule-iv', 'Medium', 'graphs', 0, 0, 1),
('https://leetcode.com/problems/number-of-connected-components-in-an-undirected-graph/', 'https://neetcode.io/problems/number-of-connected-components-in-an-undirected-graph', 'Medium', 'graphs', 1, 1, 1),
('https://leetcode.com/problems/redundant-connection/', 'https://neetcode.io/problems/redundant-connection', 'Medium', 'graphs', 0, 1, 1),
('https://leetcode.com/problems/accounts-merge/', 'https://neetcode.io/problems/accounts-merge', 'Medium', 'graphs', 0, 0, 1),
('https://leetcode.com/problems/evaluate-division/', 'https://neetcode.io/problems/evaluate-division', 'Medium', 'graphs', 0, 0, 1),
('https://leetcode.com/problems/minimum-height-trees/', 'https://neetcode.io/problems/minimum-height-trees', 'Medium', 'graphs', 0, 0, 1),
('https://leetcode.com/problems/word-ladder/', 'https://neetcode.io/problems/word-ladder', 'Hard', 'graphs', 0, 1, 1),
('https://leetcode.com/problems/path-with-minimum-effort/', 'https://neetcode.io/problems/path-with-minimum-effort', 'Medium', 'advanced graphs', 0, 0, 1),
('https://leetcode.com/problems/network-delay-time/', 'https://neetcode.io/problems/network-delay-time', 'Medium', 'advanced graphs', 0, 1, 1),
('https://leetcode.com/problems/reconstruct-itinerary/', 'https://neetcode.io/problems/reconstruct-itinerary', 'Hard', 'advanced graphs', 0, 1, 1),
('https://leetcode.com/problems/min-cost-to-connect-all-points/', 'https://neetcode.io/problems/min-cost-to-connect-all-points', 'Medium', 'advanced graphs', 0, 1, 1),
('https://leetcode.com/problems/swim-in-rising-water/', 'https://neetcode.io/problems/swim-in-rising-water', 'Hard', 'advanced graphs', 0, 1, 1),
('https://leetcode.com/problems/alien-dictionary/', 'https://neetcode.io/problems/alien-dictionary', 'Hard', 'advanced graphs', 1, 1, 1),
('https://leetcode.com/problems/cheapest-flights-within-k-stops/', 'https://neetcode.io/problems/cheapest-flights-within-k-stops', 'Medium', 'advanced graphs', 0, 1, 1),
('https://leetcode.com/problems/find-critical-and-pseudo-critical-edges-in-minimum-spanning-tree/', 'https://neetcode.io/problems/find-critical-and-pseudo-critical-edges-in-minimum-spanning-tree', 'Hard', 'advanced graphs', 0, 0, 1),
('https://leetcode.com/problems/build-a-matrix-with-conditions/', 'https://neetcode.io/problems/build-a-matrix-with-conditions', 'Hard', 'advanced graphs', 0, 0, 1),
('https://leetcode.com/problems/greatest-common-divisor-traversal/', 'https://neetcode.io/problems/greatest-common-divisor-traversal', 'Hard', 'advanced graphs', 0, 0, 1),
('https://leetcode.com/problems/climbing-stairs/', 'https://neetcode.io/problems/climbing-stairs', 'Easy', '1D dynamic programming', 1, 1, 1),
('https://leetcode.com/problems/min-cost-climbing-stairs/', 'https://neetcode.io/problems/min-cost-climbing-stairs', 'Easy', '1D dynamic programming', 0, 1, 1),
('https://leetcode.com/problems/n-th-tribonacci-number/', 'https://neetcode.io/problems/n-th-tribonacci-number', 'Easy', '1D dynamic programming', 0, 0, 1),
('https://leetcode.com/problems/house-robber/', 'https://neetcode.io/problems/house-robber', 'Medium', '1D dynamic programming', 1, 1, 1),
('https://leetcode.com/problems/house-robber-ii/', 'https://neetcode.io/problems/house-robber-ii', 'Medium', '1D dynamic programming', 1, 1, 1),
('https://leetcode.com/problems/longest-palindromic-substring/', 'https://neetcode.io/problems/longest-palindromic-substring', 'Medium', '1D dynamic programming', 1, 1, 1),
('https://leetcode.com/problems/palindromic-substrings/', 'https://neetcode.io/problems/palindromic-substrings', 'Medium', '1D dynamic programming', 1, 1, 1),
('https://leetcode.com/problems/decode-ways/', 'https://neetcode.io/problems/decode-ways', 'Medium', '1D dynamic programming', 1, 1, 1),
('https://leetcode.com/problems/coin-change/', 'https://neetcode.io/problems/coin-change', 'Medium', '1D dynamic programming', 1, 1, 1),
('https://leetcode.com/problems/maximum-product-subarray/', 'https://neetcode.io/problems/maximum-product-subarray', 'Medium', '1D dynamic programming', 1, 1, 1),
('https://leetcode.com/problems/word-break/', 'https://neetcode.io/problems/word-break', 'Medium', '1D dynamic programming', 1, 1, 1),
('https://leetcode.com/problems/longest-increasing-subsequence/', 'https://neetcode.io/problems/longest-increasing-subsequence', 'Medium', '1D dynamic programming', 1, 1, 1),
('https://leetcode.com/problems/partition-equal-subset-sum/', 'https://neetcode.io/problems/partition-equal-subset-sum', 'Medium', '1D dynamic programming', 0, 1, 1),
('https://leetcode.com/problems/combination-sum-iv/', 'https://neetcode.io/problems/combination-sum-iv', 'Medium', '1D dynamic programming', 0, 0, 1),
('https://leetcode.com/problems/perfect-squares/', 'https://neetcode.io/problems/perfect-squares', 'Medium', '1D dynamic programming', 0, 0, 1),
('https://leetcode.com/problems/integer-break/', 'https://neetcode.io/problems/integer-break', 'Medium', '1D dynamic programming', 0, 0, 1),
('https://leetcode.com/problems/stone-game-iii/', 'https://neetcode.io/problems/stone-game-iii', 'Hard', '1D dynamic programming', 0, 0, 1),
('https://leetcode.com/problems/unique-paths/', 'https://neetcode.io/problems/unique-paths', 'Medium', '2D dynamic programming', 1, 1, 1),
('https://leetcode.com/problems/unique-paths-ii/', 'https://neetcode.io/problems/unique-paths-ii', 'Medium', '2D dynamic programming', 0, 0, 1),
('https://leetcode.com/problems/minimum-path-sum/', 'https://neetcode.io/problems/minimum-path-sum', 'Medium', '2D dynamic programming', 0, 0, 1),
('https://leetcode.com/problems/longest-common-subsequence/', 'https://neetcode.io/problems/longest-common-subsequence', 'Medium', '2D dynamic programming', 1, 1, 1),
('https://leetcode.com/problems/last-stone-weight-ii/', 'https://neetcode.io/problems/last-stone-weight-ii', 'Medium', '2D dynamic programming', 0, 0, 1),
('https://leetcode.com/problems/best-time-to-buy-and-sell-stock-with-cooldown/', 'https://neetcode.io/problems/best-time-to-buy-and-sell-stock-with-cooldown', 'Medium', '2D dynamic programming', 0, 1, 1),
('https://leetcode.com/problems/coin-change-ii/', 'https://neetcode.io/problems/coin-change-ii', 'Medium', '2D dynamic programming', 0, 1, 1),
('https://leetcode.com/problems/target-sum/', 'https://neetcode.io/problems/target-sum', 'Medium', '2D dynamic programming', 0, 1, 1),
('https://leetcode.com/problems/interleaving-string/', 'https://neetcode.io/problems/interleaving-string', 'Medium', '2D dynamic programming', 0, 1, 1),
('https://leetcode.com/problems/stone-game/', 'https://neetcode.io/problems/stone-game', 'Medium', '2D dynamic programming', 0, 0, 1);
--> statement-breakpoint
INSERT INTO `neetcode` (`leetcode_question_link`, `neetcode_question_link`, `difficulty`, `tag`, `blind_75`, `neetcode_150`, `neetcode_250`) VALUES
('https://leetcode.com/problems/stone-game-ii/', 'https://neetcode.io/problems/stone-game-ii', 'Medium', '2D dynamic programming', 0, 0, 1),
('https://leetcode.com/problems/longest-increasing-path-in-a-matrix/', 'https://neetcode.io/problems/longest-increasing-path-in-a-matrix', 'Hard', '2D dynamic programming', 0, 1, 1),
('https://leetcode.com/problems/distinct-subsequences/', 'https://neetcode.io/problems/distinct-subsequences', 'Hard', '2D dynamic programming', 0, 1, 1),
('https://leetcode.com/problems/edit-distance/', 'https://neetcode.io/problems/edit-distance', 'Medium', '2D dynamic programming', 0, 1, 1),
('https://leetcode.com/problems/burst-balloons/', 'https://neetcode.io/problems/burst-balloons', 'Hard', '2D dynamic programming', 0, 1, 1),
('https://leetcode.com/problems/regular-expression-matching/', 'https://neetcode.io/problems/regular-expression-matching', 'Hard', '2D dynamic programming', 0, 1, 1),
('https://leetcode.com/problems/lemonade-change/', 'https://neetcode.io/problems/lemonade-change', 'Easy', 'greedy', 0, 0, 1),
('https://leetcode.com/problems/maximum-subarray/', 'https://neetcode.io/problems/maximum-subarray', 'Medium', 'greedy', 1, 1, 1),
('https://leetcode.com/problems/maximum-sum-circular-subarray/', 'https://neetcode.io/problems/maximum-sum-circular-subarray', 'Medium', 'greedy', 0, 0, 1),
('https://leetcode.com/problems/longest-turbulent-array/', 'https://neetcode.io/problems/longest-turbulent-array', 'Medium', 'greedy', 0, 0, 1),
('https://leetcode.com/problems/jump-game/', 'https://neetcode.io/problems/jump-game', 'Medium', 'greedy', 1, 1, 1),
('https://leetcode.com/problems/jump-game-ii/', 'https://neetcode.io/problems/jump-game-ii', 'Medium', 'greedy', 0, 1, 1),
('https://leetcode.com/problems/jump-game-vii/', 'https://neetcode.io/problems/jump-game-vii', 'Medium', 'greedy', 0, 0, 1),
('https://leetcode.com/problems/gas-station/', 'https://neetcode.io/problems/gas-station', 'Medium', 'greedy', 0, 1, 1),
('https://leetcode.com/problems/hand-of-straights/', 'https://neetcode.io/problems/hand-of-straights', 'Medium', 'greedy', 0, 1, 1),
('https://leetcode.com/problems/dota2-senate/', 'https://neetcode.io/problems/dota2-senate', 'Medium', 'greedy', 0, 0, 1),
('https://leetcode.com/problems/merge-triplets-to-form-target-triplet/', 'https://neetcode.io/problems/merge-triplets-to-form-target-triplet', 'Medium', 'greedy', 0, 1, 1),
('https://leetcode.com/problems/partition-labels/', 'https://neetcode.io/problems/partition-labels', 'Medium', 'greedy', 0, 1, 1),
('https://leetcode.com/problems/valid-parenthesis-string/', 'https://neetcode.io/problems/valid-parenthesis-string', 'Medium', 'greedy', 0, 1, 1),
('https://leetcode.com/problems/candy/', 'https://neetcode.io/problems/candy', 'Hard', 'greedy', 0, 0, 1),
('https://leetcode.com/problems/insert-interval/', 'https://neetcode.io/problems/insert-interval', 'Medium', 'intervals', 1, 1, 1),
('https://leetcode.com/problems/merge-intervals/', 'https://neetcode.io/problems/merge-intervals', 'Medium', 'intervals', 1, 1, 1),
('https://leetcode.com/problems/non-overlapping-intervals/', 'https://neetcode.io/problems/non-overlapping-intervals', 'Medium', 'intervals', 1, 1, 1),
('https://leetcode.com/problems/meeting-rooms/', 'https://neetcode.io/problems/meeting-rooms', 'Easy', 'intervals', 1, 1, 1),
('https://leetcode.com/problems/meeting-rooms-ii/', 'https://neetcode.io/problems/meeting-rooms-ii', 'Medium', 'intervals', 1, 1, 1),
('https://leetcode.com/problems/meeting-rooms-iii/', 'https://neetcode.io/problems/meeting-rooms-iii', 'Hard', 'intervals', 0, 0, 1),
('https://leetcode.com/problems/minimum-interval-to-include-each-query/', 'https://neetcode.io/problems/minimum-interval-to-include-each-query', 'Hard', 'intervals', 0, 1, 1),
('https://leetcode.com/problems/excel-sheet-column-title/', 'https://neetcode.io/problems/excel-sheet-column-title', 'Easy', 'math and geometry', 0, 0, 1),
('https://leetcode.com/problems/greatest-common-divisor-of-strings/', 'https://neetcode.io/problems/greatest-common-divisor-of-strings', 'Easy', 'math and geometry', 0, 0, 1),
('https://leetcode.com/problems/insert-greatest-common-divisors-in-linked-list/', 'https://neetcode.io/problems/insert-greatest-common-divisors-in-linked-list', 'Medium', 'math and geometry', 0, 0, 1),
('https://leetcode.com/problems/transpose-matrix/', 'https://neetcode.io/problems/transpose-matrix', 'Easy', 'math and geometry', 0, 0, 1),
('https://leetcode.com/problems/rotate-image/', 'https://neetcode.io/problems/rotate-image', 'Medium', 'math and geometry', 1, 1, 1),
('https://leetcode.com/problems/spiral-matrix/', 'https://neetcode.io/problems/spiral-matrix', 'Medium', 'math and geometry', 1, 1, 1),
('https://leetcode.com/problems/set-matrix-zeroes/', 'https://neetcode.io/problems/set-matrix-zeroes', 'Medium', 'math and geometry', 1, 1, 1),
('https://leetcode.com/problems/happy-number/', 'https://neetcode.io/problems/happy-number', 'Easy', 'math and geometry', 0, 1, 1),
('https://leetcode.com/problems/plus-one/', 'https://neetcode.io/problems/plus-one', 'Easy', 'math and geometry', 0, 1, 1),
('https://leetcode.com/problems/roman-to-integer/', 'https://neetcode.io/problems/roman-to-integer', 'Easy', 'math and geometry', 0, 0, 1),
('https://leetcode.com/problems/powx-n/', 'https://neetcode.io/problems/powx-n', 'Medium', 'math and geometry', 0, 1, 1),
('https://leetcode.com/problems/multiply-strings/', 'https://neetcode.io/problems/multiply-strings', 'Medium', 'math and geometry', 0, 1, 1),
('https://leetcode.com/problems/detect-squares/', 'https://neetcode.io/problems/detect-squares', 'Medium', 'math and geometry', 0, 1, 1),
('https://leetcode.com/problems/single-number/', 'https://neetcode.io/problems/single-number', 'Easy', 'bit manipulation', 0, 1, 1),
('https://leetcode.com/problems/number-of-1-bits/', 'https://neetcode.io/problems/number-of-1-bits', 'Easy', 'bit manipulation', 1, 1, 1),
('https://leetcode.com/problems/counting-bits/', 'https://neetcode.io/problems/counting-bits', 'Easy', 'bit manipulation', 1, 1, 1),
('https://leetcode.com/problems/add-binary/', 'https://neetcode.io/problems/add-binary', 'Easy', 'bit manipulation', 0, 0, 1),
('https://leetcode.com/problems/reverse-bits/', 'https://neetcode.io/problems/reverse-bits', 'Easy', 'bit manipulation', 1, 1, 1),
('https://leetcode.com/problems/missing-number/', 'https://neetcode.io/problems/missing-number', 'Easy', 'bit manipulation', 1, 1, 1),
('https://leetcode.com/problems/sum-of-two-integers/', 'https://neetcode.io/problems/sum-of-two-integers', 'Medium', 'bit manipulation', 1, 1, 1),
('https://leetcode.com/problems/reverse-integer/', 'https://neetcode.io/problems/reverse-integer', 'Medium', 'bit manipulation', 0, 1, 1),
('https://leetcode.com/problems/bitwise-and-of-numbers-range/', 'https://neetcode.io/problems/bitwise-and-of-numbers-range', 'Medium', 'bit manipulation', 0, 0, 1),
('https://leetcode.com/problems/minimum-array-end/', 'https://neetcode.io/problems/minimum-array-end', 'Medium', 'bit manipulation', 0, 0, 1);
